Changed gradle and hooks.

diff --git a/.github/hooks/pre-commit b/.github/hooks/pre-commit
--- a/.github/hooks/pre-commit
+++ b/.github/hooks/pre-commit
@@ -1,10 +1,14 @@
 #!/bin/sh
+
+# Move to the root of the repository
+cd "$(git rev-parse --show-toplevel)" || exit 1
+
 # Check for staged Kotlin files
 if git diff --cached --name-only | grep -E '\.kt$' > /dev/null; then
-  echo "running ktlintCheck"
+  echo "Running ktlintCheck..."
   ./gradlew ktlintCheck
   if [ $? -ne 0 ]; then
-    echo "ktlint check failed, running ktlintFormat"
+    echo "ktlint check failed, running ktlintFormat..."
     ./gradlew ktlintFormat
     exit 1
   fi
diff --git a/.github/hooks/pre-push b/.github/hooks/pre-push
--- a/.github/hooks/pre-push
+++ b/.github/hooks/pre-push
@@ -1,10 +1,15 @@
 #!/bin/sh
 echo "Executing pre-push hook..."
+echo "Running build..."
 
-echo "running build"
+# Move to repo root
+cd "$(git rev-parse --show-toplevel)" || exit 1
 
+# Run Gradle build
 ./gradlew build
 if [ $? -ne 0 ]; then
-  echo "build failed, fix issues before committing this"
+  echo "Build failed, fix issues before committing this"
   exit 1
 fi
+
+echo "Build succeeded."
